# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SongBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SongBook
    pod 'SnapKit'
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'FirebaseUI'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Phone'
end
target ‘SongBookUnitTests’ do
 inherit! :search_paths
 # Pods for testing
 end
target ‘SongBookUITests’ do
 inherit! :search_paths
 # Pods for testing
 end
